### ISSUE TITLE
structurizr-adr-tools 1.3.8 doesn't work with structurizr-core 1.14.1

### ISSUE THREAD

**Issue by guepardo190889** [structurizr/java-extensions#67]
I am using structurizr-core 1.14.1 and I want to use structurizr-adr-tools.

structurizr-adr-tools 1.3.8 is the latest version available but it is not supported. I am getting the following error:
java.lang.NoClassDefFoundError: com/structurizr/documentation/DecisionStatus
![error_structurizr](https://user-images.githubusercontent.com/257324/191991477-7261ee52-aea2-4f39-9c79-b32419fe152c.png)

**Comment by simonbrowndotje** [comment]
The documentation and ADR parsing code has all moved to a new module named `structurizr-documentation`:

- GitHub repo -> https://github.com/structurizr/documentation
- Maven -> https://mvnrepository.com/artifact/com.structurizr/structurizr-documentation

I will add a note to this repo.

**Comment by guepardo190889** [comment]
It works now!

This example helped me a lot: https://github.com/structurizr/examples/blob/main/java/src/main/java/com/structurizr/example/adrtools/AdrTools.java

Thank you very much!
